window.GOYAL_PRODUCTS=[
{"category":"Wires & Cables","range":"Life Shield","product_name":"Life Shield HFFR Industrial Cable 180m","size":"1.00 sq mm","code":"WHFFFN-L11X07","list_price":6980},
{"category":"Wires & Cables","range":"Life Shield","product_name":"Life Shield HFFR Industrial Cable 180m","size":"1.50 sq mm","code":"WHFFFN-L11X57","list_price":10210},
{"category":"Wires & Cables","range":"Life Shield","product_name":"Life Shield HFFR Industrial Cable 180m","size":"2.50 sq mm","code":"WHFFFN-L12X57","list_price":16690},
{"category":"Wires & Cables","range":"Life Shield","product_name":"Life Shield HFFR Industrial Cable 180m","size":"4.00 sq mm","code":"WHFFFN-L14X07","list_price":25770},
{"category":"Wires & Cables","range":"Life Shield","product_name":"Life Shield HFFR Industrial Cable 180m","size":"6.00 sq mm","code":"WHFFFN-L16X07","list_price":38600},
{"category":"Wires & Cables","range":"Life Guard","product_name":"Life Guard FR-LSH PVC Industrial Cable 180m","size":"1.00 sq mm","list_price":7105},
{"category":"Wires & Cables","range":"Life Guard","product_name":"Life Guard FR-LSH PVC Industrial Cable 180m","size":"1.50 sq mm","list_price":10415},
{"category":"Wires & Cables","range":"Life Guard","product_name":"Life Guard FR-LSH PVC Industrial Cable 180m","size":"2.50 sq mm","list_price":17020},
{"category":"Wires & Cables","range":"Life Guard","product_name":"Life Guard FR-LSH PVC Industrial Cable 180m","size":"4.00 sq mm","list_price":26265},
{"category":"Wires & Cables","range":"Life Guard","product_name":"Life Guard FR-LSH PVC Industrial Cable 180m","size":"6.00 sq mm","list_price":39350},
{"category":"Wires & Cables","range":"FR PVC","product_name":"FR PVC Cable 180m","size":"0.75 sq mm","list_price":5240},
{"category":"Wires & Cables","range":"FR PVC","product_name":"FR PVC Cable 180m","size":"1.00 sq mm","list_price":6770},
{"category":"Wires & Cables","range":"FR PVC","product_name":"FR PVC Cable 180m","size":"1.50 sq mm","list_price":9920},
{"category":"Wires & Cables","range":"FR PVC","product_name":"FR PVC Cable 180m","size":"2.50 sq mm","list_price":16205},
{"category":"Wires & Cables","range":"FR PVC","product_name":"FR PVC Cable 180m","size":"4.00 sq mm","list_price":25030},
{"category":"Wires & Cables","range":"FR PVC","product_name":"FR PVC Cable 180m","size":"6.00 sq mm","list_price":37475},
{"category":"Wires & Cables","range":"Life Shield","product_name":"Life Shield HFFR Industrial Cable 90m","size":"1.00 sq mm","list_price":3370},
{"category":"Wires & Cables","range":"Life Shield","product_name":"Life Shield HFFR Industrial Cable 90m","size":"1.50 sq mm","list_price":4925},
{"category":"Wires & Cables","range":"Life Shield","product_name":"Life Shield HFFR Industrial Cable 90m","size":"2.50 sq mm","list_price":7820},
{"category":"Wires & Cables","range":"Life Shield","product_name":"Life Shield HFFR Industrial Cable 90m","size":"4.00 sq mm","list_price":11460},
{"category":"Wires & Cables","range":"Life Shield","product_name":"Life Shield HFFR Industrial Cable 90m","size":"6.00 sq mm","list_price":17060},
{"category":"Switches & Accessories","range":"Adiva","product_name":"Adiva 6 AX 1 Way Switch White","size":"6 AX","color":"White","list_price":41},
{"category":"Switches & Accessories","range":"Adiva","product_name":"Adiva 6 AX 1 Way Switch Grey/Black","size":"6 AX","color":"Grey/Black","list_price":52},
{"category":"Switches & Accessories","range":"Adiva","product_name":"Adiva 6 AX 2 Way Switch White","size":"6 AX","color":"White","list_price":119},
{"category":"Switches & Accessories","range":"Adiva","product_name":"Adiva 6 AX 2 Way Switch Grey/Black","size":"6 AX","color":"Grey/Black","list_price":145},
{"category":"Switches & Accessories","range":"Adiva","product_name":"Adiva 16 AX 1 Way Switch White","size":"16 AX","color":"White","list_price":144},
{"category":"Switches & Accessories","range":"Adiva","product_name":"Adiva 16 AX 1 Way Switch Grey/Black","size":"16 AX","color":"Grey/Black","list_price":174},
{"category":"Switches & Accessories","range":"Adiva","product_name":"Adiva 20A DP 1 Way Indicator Switch White","size":"20A DP","color":"White","list_price":284},
{"category":"Switches & Accessories","range":"Adiva","product_name":"Adiva 20A DP 1 Way Indicator Switch Grey/Black","size":"20A DP","color":"Grey/Black","list_price":345},
{"category":"Switches & Accessories","range":"YU","product_name":"YU 6 AX 1 Way Switch White","size":"6 AX","color":"White","list_price":55},
{"category":"Switches & Accessories","range":"YU","product_name":"YU 6 AX 1 Way Switch Grey","size":"6 AX","color":"Grey","list_price":70},
{"category":"Switches & Accessories","range":"YU","product_name":"YU 6 AX 2 Way Switch","size":"6 AX","list_price":80}
];